### PR TITLE
docs: add test of ref arch

### PR DESCRIPTION
**Pull request by SirSpidey**
### Description

Adds reference architecture "source" to test how we pull it into Cloud Docs

**Check the relevant boxes:**
- [ ] Bug fix (nonbreaking change that fixes an issue)
- [ ] New feature (nonbreaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Examples or tests (addition or updates of examples or tests)
- [x] Documentation update
- [ ] CI related update (pipeline, etc.)

### Checklist

- [ ] If relevant, a test for the change has been added or updated as part of this PR.
- [ ] If relevant, documentation for the change has been added or updated as part of this PR.

### Merge

- Merge using "Squash and merge".
- Make sure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents. The commit message determines whether a new version of the modules needs to be released, and if so, which semver number to use).

### CODE REVIEW

**Comment by ocofaigh** [comment]
Hey @SirSpidey was this PR supposed to be for this repo? This repo is only used for testing things like pipeline changes

**Comment by SirSpidey** [comment]
@ocofaigh I picked this one in your absence yesterday as a place to test some Docs code to bring in ref architectures to Cloud Docs from the modules. We can remove these files after the test. Is there a better repo to use for a test?

**Comment by ocofaigh** [comment]
Ah ok thats no problem @SirSpidey - this repo is fine to use for such a test. Was just making sure it wasn't supposed to be in a different repo. Do you need this merged?

**Comment by SirSpidey** [comment]
@ocofaigh Yes please merge. Thanks.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
